import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="dark">
            <body className="dark:bg-body bg-white font-[Sora] dark:text-white text-dark">
                <Header />
                <main>
                    <div className="main-container container grid lg:grid-cols-[218px_1fr] gap-[3.5rem]">
                        {children}
                    </div>
                </main>
                <Footer />
                <div id="modal-root-content" />
            </body>
        </html>
    );
}
